### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by itsam** [deskoh/feathers-authentication-oidc#20]
Hello,
after `npm install feathers-authentication-oidc` I need to go inside node_modules/feathers-authentication-oidc and run `npm i` and `npm run-script build` in order for the package to work properly... is this normal?

Thank you in advance

**Comment by deskoh** [comment]
What is the error you encountered? Any error message?

**Comment by itsam** [comment]
Yes, the error is 
`Error: Cannot find module '/xxxx/xxxxx/xxxx/node_modules/feathers-authentication-oidc/lib'. Please verify that the package.json has a valid "main" entry`

`
 code: 'MODULE_NOT_FOUND',
  path: '/xxxxx/xxxxxx/xxxxx/node_modules/feathers-authentication-oidc/package.json',
  requestPath: 'feathers-authentication-oidc'
`

The main entry is set to "lib" but there's no lib folder included.
In order to create the lib folder you have to `cd` in the above path and run `npm i` and then build...

As you understand, the npm package should contain the /lib when you `yarn add` or `npm install feathers-authentication-oidc`

Hope this clarifies the issue
Best

**Comment by deskoh** [comment]
thanks for catching it! re-released as 0.4.4.

**Comment by itsam** [comment]
Hello, I confirm it works as expected. Thank you for prompt actions :)
